Reload changed source files (integration test and KafkaNodeContainer)
emc-mongoose/mongoose-storage-driver-kafka pull request #20
Opened 2019-04-03 23:23 UTC by ivan-abc

“Signed-off-by: [Ivan Sysoev] [ivanabc97@gmail.com]”

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

2019-04-14 22:28 UTC, paulgrape commented
Tests failed because of outdated gitlab-ci.yaml file.
It would be better to rebase last changes from master branch.

2019-04-15 06:13 UTC, akurilov requested changes

2019-04-15 06:13 UTC, akurilov commented on README.md
> +| storage-driver-compression-type | string | none | The compression type for all data generated by the producer. The default is none (i.e. no compression). Valid values are none, gzip, snappy, lz4, o
let it be the default value to be `null` (meaning "none")
also, the type is enum rather than string

2019-04-18 12:59 UTC, akurilov requested changes

2019-04-18 12:59 UTC, akurilov commented on README.md
> +| storage-driver-compression-type | enum | null | The compression type for all data generated by the producer. The default is none (i.e. no compression). Valid values are none, gzip, snappy, lz4, or
"Valid values are `null`, "gzip"..."

2019-04-18 12:59 UTC, akurilov commented on src/main/resources/defaults-storage-driver-kafka.yml
> +      type: none
null

2019-04-23 09:06 UTC, akurilov approved these changes

2019-04-25 11:25 UTC, merged