Add example of Custom Kafka Headers
emc-mongoose/mongoose-storage-driver-kafka pull request #29
Opened 2019-04-14 15:04 UTC by oleg-rakitin

2019-04-15 06:08 UTC, akurilov submitted a review, later dismissed

2019-04-15 06:08 UTC, akurilov commented on README.md
> +        "net" : {
let's use `storage-driver-request-headers` either `storage-driver-create-headers` option
also, the doc is updated, but the option is not added into the defaults/schema yaml files
moreover, the declared configuration option should be handled by the driver's code

2019-04-15 06:20 UTC, AndreyKoltsov1997 submitted a review, later dismissed
What about the record key?

2019-04-24 05:26 UTC, akurilov submitted a review, later dismissed

2019-04-24 05:26 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/kafka/KafkaStorageDriver.java
> +        throw new IllegalArgumentException("Unsupported key");
the constant headers should be used also

2019-05-02 19:25 UTC, akurilov requested changes

2019-05-02 19:25 UTC, akurilov commented on src/main/resources/config/defaults-storage-driver-kafka.yml
> +        Connection: Keep-Alive
this is HTTP-specific headers which are not suitable for kafka
let's leave the headers empty

2019-05-05 13:00 UTC, akurilov requested changes

2019-05-05 13:00 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/kafka/KafkaStorageDriver.java
> +    for (final var header : headersMap.entrySet()) {
the default value will cause NullPointerException here

2019-05-05 13:00 UTC, akurilov commented on src/main/resources/config/defaults-storage-driver-kafka.yml
> +      headers: null
https://stackoverflow.com/questions/33510094/syntax-for-empty-dictionary-in-yaml

2019-05-13 06:20 UTC, akurilov approved these changes

2019-05-13 11:55 UTC, merged