Kafka start instructions
emc-mongoose/mongoose-storage-driver-kafka pull request #49
Opened 2019-06-16 13:47 UTC by oleg-rakitin

2019-06-17 06:09 UTC, akurilov approved these changes

2019-06-17 06:09 UTC, akurilov commented on README.md
> ++ Run Mongoose ```java -jar mongoose-base-x.x.xx.jar - store-driver-type = kafka ...```
```
--storage-driver-type=kafka \
--storage-driver-limit-queue-input=10000 \
--load-batch-size=100 \
...
```

2019-06-17 06:09 UTC, akurilov commented on README.md
> ++ Build Kafka storage driver and put in .mongoose\version_of_mongoose\ext
It's important that `.mongoose` directory is in the home directory. I usually refer this as `~/.mongoose`.

2019-06-17 06:17 UTC, akurilov requested changes
see the previous comments

2019-06-24 13:38 UTC, veronikaKochugova approved these changes

2019-06-30 18:17 UTC, closed without merging